LANG_EN = {
    "welcome": "Welcome to Smart Library CLI",
    "prompt_cmd": "Enter command number",
    "err_unknown": "Unknown command",
    "err_not_found": "Book not found",
    "err_remove": "Error while removing the book",
    "err_occurred": "An error occurred",
    "err_unknown": "Unknown command",
    "title_books": "Books",
    "title_list": "Book List",
    "title_search": "Search results for",
    "title_favorites": "Favorite Books",
    "title_recs": "Recommendations",
    "col_title": "Title",
    "col_author": "Author",
    "col_genre": "Genre",
    "col_year": "Year",
    "col_status": "Status",
    "col_fav": "Favorite",
    "status_read": "Read",
    "status_unread": "Unread",
    "status_favs": "Favorites",
    "msg_no_desc": "(no description)",
    "msg_added_success": "Book was added successfully",
    "msg_changes_success": "Changes saved successfully",
    "msg_removed_success": "Book was removed successfully",
    "msg_no_favorites": "No favorite books",
    "msg_no_recs": "No recommendations — add more books or mark some as read",
    "msg_quit": "Quit — data saved successfully.",
    "lbl_add": "Add new book",
    "lbl_browse": "Browse books",
    "lbl_search": "Search book",
    "lbl_fav_change": "Add/Remove from favorites and change status",
    "lbl_remove": "Remove book",
    "lbl_chosen": "Chosen",
    "q_details": "Show details by title?",
    "q_title": "Enter book title",
    "q_keyword": "Enter keyword (in title, author or description)",
    "q_mark_unread": "Mark as unread?",
    "q_mark_read": "Mark as read?",
    "q_rem_fav": "Remove from favorites?",
    "q_add_fav": "Add to favorites?",
    "q_add_rec_fav": "Add recommendation to favorites?",
    "q_title_rem": "Enter book title to remove",
    "q_confirm_rem": "Are you sure you want to remove this book?",
    "menu_add": " Add book",
    "menu_browse": " Browse books",
    "menu_search": " Search book",
    "menu_favs": " Favorite books",
    "menu_edit": " Edit status/favorites",
    "menu_recs": " Recommendations",
    "menu_remove": " Remove book",
    "menu_exit": " Exit",
    "menu_title": "Smart Library CLI",
    "menu_sub": "Choose action"
}
