[project]
name = "smart-library-cli"
version = "1.0.0"
description = "A lightweight object-oriented CLI application for managing book inventories with a rich TUI."
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "lifer-x" }
]
keywords = ["cli", "tui", "library-management", "rich", "oop"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Database :: Front-Ends"
]
dependencies = [
    "rich>=13.0.0",
]

[tool.uv]
managed = true

[project.scripts]
smart-library = "library_project.main:main"
